import {
  getMovieById,
  getTvShowById,
  getTrendingCombined,
  getTopRatedMovies,
  getMoviesByGenre,
  getTopRatedTv,
  getTvByGenre,
  getSearchResults,
  addItemToRecentSearches,
  getRecentSearches,
  removeItemFromRecentSearches,
  toggleItemToWatchList,
  getWatchList,
  getVisionSearchData,
} from './storage.service';

export {
  getMovieById,
  getTvShowById,
  getTrendingCombined,
  getTopRatedMovies,
  getMoviesByGenre,
  getTopRatedTv,
  getTvByGenre,
  getSearchResults,
  addItemToRecentSearches,
  getRecentSearches,
  removeItemFromRecentSearches,
  toggleItemToWatchList,
  getWatchList,
  getVisionSearchData,
};
