import {
  getMovieById,
  getTvShowById,
  getTrendingCombined,
  getTopRatedMovies,
  getMoviesByGenre,
  getTopRatedTv,
  getTvByGenre,
  getSearchResults,
  addItemToRecentSearches,
  getRecentSearches,
  removeItemFromRecentSearches,
  getVisionResults,
  toggleItemToWatchList,
  getWatchList,
  getVisionSearchData,
  getPersonById,
  getDiscover,
} from './storage.service';

export {
  getMovieById,
  getTvShowById,
  getTrendingCombined,
  getTopRatedMovies,
  getMoviesByGenre,
  getTopRatedTv,
  getTvByGenre,
  getSearchResults,
  addItemToRecentSearches,
  getRecentSearches,
  removeItemFromRecentSearches,
  getVisionResults,
  toggleItemToWatchList,
  getWatchList,
  getVisionSearchData,
  getPersonById,
  getDiscover,
};
